name: Pull Request Open Comment

on:
  pull_request_target:
    types:
      - "opened"
    branches:
      - "master"

permissions:
  issues: write
  pull-requests: write

jobs:
  comment_on_open:
    if: github.repository == 'codinasion/codinasion-programme' && github.event.pull_request.base.ref == github.event.repository.default_branch && github.event.pull_request.user.login != 'harshraj8843'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: `💖 Thanks for opening this issue. 💖 

              A Codinasion team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/codinasion/codinasion-programme/blob/master/CONTRIBUTING.md).`
            })
